import { LessonCategory } from "@/models/Lesson";

export interface SeedLesson {
  title: string;
  slug: string;
  sectionNumber: number;
  category: LessonCategory;
  order: number;
  content: string;
}

export const seedLessons: SeedLesson[] = [
  {
    title: "O que é o Kreyòl Ayisyen?",
    slug: "01-o-que-e-o-kreyol-ayisyen",
    sectionNumber: 1,
    category: "Gramática" as LessonCategory,
    order: 1,
    content: "# O que é o Kreyòl Ayisyen?\n\nO Kreyòl Ayisyen (crioulo haitiano) é uma língua crioula falada no Haiti e em toda a diáspora haitiana — Estados Unidos, Canadá, França, República Dominicana e, cada vez mais, no Brasil. É uma das duas línguas oficiais do Haiti, ao lado do francês, e é a língua materna da grande maioria da população. A Akademi Kreyòl Ayisyen (AKA), a academia oficial da língua, trabalha na produção de gramáticas, dicionários e materiais de padronização ortográfica, reconhecendo o Kreyòl como um sistema linguístico completo e autônomo — não como uma versão \"simplificada\" do francês. Do ponto de vista histórico, o Kreyòl surgiu do contato intenso entre o francês colonial e diversas línguas da África Ocidental faladas pelas pessoas escravizadas levadas à ilha. Desse contato nasceu uma língua nova, com gramática, fonologia e vocabulário próprios — não uma mistura aleatória, mas um sistema com regras internas coerentes.\n\n> Para a sala de aula: evite a ideia de que \"Kreyòl é francês mal falado\". Isso é um mito comum e desrespeitoso. Trate cada estrutura como parte de um sistema gramatical próprio, com sua própria lógica.",
  },
  {
    title: "\"Crioulo\" não é uma língua só",
    slug: "02-crioulo-nao-e-uma-lingua-so",
    sectionNumber: 2,
    category: "Gramática" as LessonCategory,
    order: 2,
    content: "# \"Crioulo\" não é uma língua só\n\nA palavra \"crioulo\" é um termo genérico usado para várias línguas diferentes, nascidas em diferentes contextos históricos de contato entre línguas. Isso significa que Kreyòl Ayisyen, Kreyòl Gwadloup (Guadalupe), Kreyòl Giyàn (Guiana Francesa), Morisyen (Maurício) e o crioulo de Seychelles são idiomas distintos — cada um com sua própria gramática, mesmo compartilhando uma base lexical francesa.\n\nLÍNGUA BASE / CONTEXTO HISTÓRICO PONTO ESTRUTURAL A OBSERVAR\n\nKreyòl Ayisyen Forte componente lexical francês + línguas africanas e Partículas de tempo/aspecto, determinantes pós-nominais, outros contatos históricos pronomes e sintaxe próprios\n\nKreyòl Gwadloup Crioulo de base francesa do Caribe Gramática própria; não é uma variedade do haitiano\n\nKreyòl Giyàn Crioulo de base francesa da Guiana Francesa Estruturas e vocabulário próprios, com gramática comparada já descrita\n\nMorisyen Crioulo de base francesa no Oceano Índico Descrição gramatical própria; trajetória histórica diferente do Haiti\n\nSeychellois Crioulo do arquipélago de Seychelles Sistema próprio, apesar de relações históricas com o francês\n\nCrioulos de base Caribe, África e outros contextos Léxico predominantemente inglês; não confundir com inglesa crioulos franceses\n\nCrioulos de base África, Ásia e outros contextos Léxico predominantemente português; estruturas variam portuguesa muito entre si\n\n> Erro comum a evitar: nunca ensine \"regras universais do crioulo\". Cada língua crioula tem sua própria história e sua própria gramática. O que vale para o haitiano não pode ser transportado automaticamente para o crioulo de Guadalupe ou para o Morisyen.",
  },
  {
    title: "Gramática comparada: por que o haitiano é único",
    slug: "03-gramatica-comparada-por-que-o-haitiano-e-unico",
    sectionNumber: 3,
    category: "Gramática" as LessonCategory,
    order: 3,
    content: "# Gramática comparada: por que o haitiano é único\n\n### 3.1 Tempo, modo e aspecto\n\nNo Kreyòl Ayisyen não existe conjugação verbal como em português. Em vez disso, partículas pré-verbais — colocadas antes do verbo — marcam tempo, modo e aspecto. As quatro mais importantes são te, ap, pral e ta.\n\n| CONSTRUÇÃO | EXEMPLO EM KREYÒL | TRADUÇÃO |\n| --- | --- | --- |\n| Presente (sem partícula) | Mwen travay. | Eu trabalho. |\n| Passado — te | Mwen te travay. | Eu trabalhei / eu trabalhava. |\n| Progressivo — ap | Mwen ap travay. | Estou trabalhando. |\n| Futuro próximo — pral | Mwen pral travay. | Vou trabalhar. |\n| Condicional/modal — ta | Mwen ta travay. | Eu trabalharia. |\n| Passado progressivo — te ap | Mwen te ap travay. | Eu estava trabalhando. |\n| Futuro distante — va / a | Mwen va travay. | Eu trabalharei (mais formal/distante). |\n\n> Mais exemplos com manje (comer): Mwen manje diri. (Eu como arroz.) · Mwen te manje diri yè. (Eu comi arroz ontem.) · Mwen ap manje kounye a. (Estou comendo agora.) · Mwen pral manje aprè klas. (Vou comer depois da aula.) · Si m te gen lajan, mwen ta manje nan restoran an. (Se eu tivesse dinheiro, eu comeria no restaurante.)\n\nA literatura linguística sobre o haitiano trata esse sistema de partículas como um campo de estudo próprio, distinto de qualquer análise baseada no francês. Por isso, o sistema te/ap/pral/ta não deve ser \"traduzido\" mentalmente a partir de tempos verbais do português — ele funciona com lógica própria.\n\n### 3.2 Ordem das palavras\n\nO Kreyòl segue tipicamente a ordem Sujeito–Verbo–Objeto (SVO): Mwen manje diri. = \"Eu como arroz.\" Perguntas, ênfase (foco/topicalização) e certos pronomes podem alterar essa ordem na superfície da frase, mas a base SVO permanece o ponto de partida pedagógico.\n\n### 3.3 Determinantes depois do substantivo\n\nDiferente do português, os marcadores definidos aparecem depois do substantivo: liv la = \"o livro\"; liv yo = \"os livros\". Esse é um dos padrões mais importantes para quebrar o hábito de traduzir palavra por palavra.\n\n### 3.4 Pronomes\n\n| PORTUGUÊS | KREYÒL | OBSERVAÇÃO |\n| --- | --- | --- |\n| eu | mwen (m) | forma reduzida \"m\" é comum na fala rápida |\n| você | ou (w) | singular; forma reduzida \"w\" antes de vogal |\n| ele/ela | li (l) | sem distinção de gênero |\n| nós | nou (n) | também pode significar \"vocês\", conforme contexto |\n| eles/elas | yo (y) | plural de 3ª pessoa |\n\n### 3.5 Cópula e \"ser/estar\"\n\nEm português, \"ser\" e \"estar\" são verbos muito frequentes. No Kreyòl, o equivalente muda conforme o tipo de predicado: Mwen se etidyan. (\"Eu sou estudante\" — com se antes de substantivo) e Mwen byen. (\"Estou bem\" — sem verbo de ligação antes de adjetivo/estado). Regra prática: não tente traduzir automaticamente cada \"ser/estar\" por uma única palavra fixa.\n\n### 3.6 Negação\n\nA partícula pa nega o verbo: Mwen pa konprann. = \"Eu não entendo.\" Ela normalmente vem logo antes do verbo (ou da partícula de tempo/aspecto): Mwen pa t ap travay. = \"Eu não estava trabalhando.\"\n\n### 3.7 Adjetivos\n\nNa maioria das construções, o adjetivo vem depois do substantivo: yon machin wouj = \"um carro vermelho\"; yon bon otèl = \"um bom hotel\"; yon bèl kote = \"um lugar bonito\". Recomenda-se memorizar blocos inteiros em vez de decorar apenas a regra abstrata.\n\n> Lembrete de comparação: outros crioulos podem ter partículas de tempo, determinantes pós-nominais ou negação parecidos na estrutura geral, mas as formas exatas e as regras de uso são diferentes em cada língua. Semelhança tipológica não é igual a identidade gramatical.",
  },
  {
    title: "Pronúncia, alfabeto e ortografia",
    slug: "04-pronuncia-alfabeto-e-ortografia",
    sectionNumber: 4,
    category: "Gramática" as LessonCategory,
    order: 4,
    content: "# Pronúncia, alfabeto e ortografia\n\nO Kreyòl usa uma ortografia oficial padronizada (diferente da ortografia francesa), em que cada letra corresponde de forma bastante regular a um som — o que facilita muito a leitura em comparação com o francês.\n\n| LETRA/DÍGRAFO | SOM APROXIMADO | EXEMPLO |\n| --- | --- | --- |\n| ch | \"x\" do português (chave) | chè (caro/querido) |\n| y | \"i\" consoante, como em \"iate\" | yo (eles) |\n| ò | \"ó\" aberto | otèl (hotel) |\n| è | \"é\" aberto | mèsi (obrigado) |\n| an, en, on | vogais nasais, como em português | lajan (dinheiro), byen (bem) |\n| r | som suave, entre \"r\" e semivogal | rele (chamar-se) |\n| j | \"j\" do português | jodi a (hoje) |\n| w | semivogal \"u\", como em \"quase\" | wi (sim) |\n\n> Atenção — falso cognato ortográfico: não confunda ou com a conjunção portuguesa \"ou\". Em Kreyòl, ou é o pronome \"você\". A conjunção \"ou\" (do português) equivale a oswa em Kreyòl.\n\n> Para a professora: a acentuação e as vogais nasais precisam ser ouvidas e praticadas com áudio de falantes nativos — nenhuma apostila escrita substitui a exposição oral. Reserve os primeiros 10 minutos de cada aula para repetição em voz alta.\n\n### 4.1 Prática de leitura em voz alta\n\nLeia em voz alta, uma linha por vez, prestando atenção às vogais nasais e ao som de ch: Bonjou. Mwen rele Marie. Mwen kontan wè ou. Ki jan ou ye? Mwen byen, mèsi anpil.",
  },
  {
    title: "Pronomes pessoais em frases",
    slug: "05-pronomes-pessoais-em-frases",
    sectionNumber: 5,
    category: "Gramática" as LessonCategory,
    order: 5,
    content: "# Pronomes pessoais em frases\n\n| KREYÒL | PORTUGUÊS |\n| --- | --- |\n| Mwen kontan. | Estou feliz. |\n| Ou pare? | Você está pronto(a)? |\n| Li la. | Ele/ela está aqui. |\n| Nou prale. | Nós vamos. |\n| Yo vini. | Eles/elas vêm / vieram. |\n| Mwen renmen ou. | Eu gosto de você / eu te amo. |\n| Nou se zanmi. | Nós somos amigos. |",
  },
  {
    title: "Determinantes, plural e demonstrativos",
    slug: "06-determinantes-plural-e-demonstrativos",
    sectionNumber: 6,
    category: "Gramática" as LessonCategory,
    order: 6,
    content: "# Determinantes, plural e demonstrativos\n\n| ESTRUTURA | EXEMPLO | SENTIDO |\n| --- | --- | --- |\n| substantivo + la | liv la | o livro |\n| substantivo + a (após vogal) | kay la → machin nan | a casa / o carro (variação fonética de \"la\") |\n| substantivo + yo | liv yo | os livros |\n| yon + substantivo | yon liv | um livro |\n| substantivo + sa | liv sa | este/esse livro |\n| substantivo + sa a | liv sa a | este livro específico (mais enfático) |\n\n> Nota: a forma do artigo definido muda de acordo com o som final da palavra anterior (la / a / an / nan). Ensine isso com exemplos memorizados, não como regra fonética abstrata para iniciantes.",
  },
  {
    title: "Possessivos",
    slug: "07-possessivos",
    sectionNumber: 7,
    category: "Gramática" as LessonCategory,
    order: 7,
    content: "# Possessivos\n\n| PORTUGUÊS | KREYÒL | EXEMPLO |\n| --- | --- | --- |\n| meu/minha | mwen | liv mwen (meu livro) |\n| seu/sua (de você) | ou | liv ou (seu livro) |\n| dele/dela | li | liv li (o livro dele/dela) |\n| nosso/nossa | nou | liv nou (nosso livro) |\n| deles/delas | yo | liv yo (o livro deles — atenção: também pode ser \"os livros\") |\n\n> Ambiguidade a explicar em aula: liv yo pode significar \"os livros\" (plural) ou \"o livro deles\" (posse), dependendo do contexto. O contexto da frase inteira resolve a ambiguidade.",
  },
  {
    title: "Verbos, tempo e aspecto",
    slug: "08-verbos-tempo-e-aspecto",
    sectionNumber: 8,
    category: "Gramática" as LessonCategory,
    order: 8,
    content: "# Verbos, tempo e aspecto\n\nUma grande vantagem pedagógica do Kreyòl é que o verbo tem uma única forma — não há conjugação por pessoa como em português. O aluno aprende o verbo uma vez e depois aprende as partículas (te/ap/pral/ta) para situá-lo no tempo.\n\n| FORMA | EXEMPLO COM MANJE (COMER) | PORTUGUÊS |\n| --- | --- | --- |\n| Presente | Mwen manje. | Eu como. |\n| Passado | Mwen te manje. | Eu comi / comia. |\n| Progressivo | Mwen ap manje. | Estou comendo. |\n| Futuro próximo | Mwen pral manje. | Vou comer. |\n| Condicional | Mwen ta manje. | Eu comeria. |\n\n### 8.1 Trinta verbos essenciais\n\n| KREYÒL | PORTUGUÊS | KREYÒL | PORTUGUÊS |\n| --- | --- | --- | --- |\n| ale | ir | vann | vender |\n| vini | vir | travay | trabalhar |\n| fè | fazer | aprann | aprender |\n| gen | ter | anseye | ensinar |\n| bay | dar | dòmi | dormir |\n| pran | pegar/tomar | leve | levantar/acordar |\n| vle | querer | mache | andar/caminhar |\n| kapab / ka | poder/conseguir | kouri | correr |\n| bezwen | precisar | gade | olhar/assistir |\n| konnen | saber/conhecer | tande | ouvir |\n| konprann | entender | wè | ver |\n| pale | falar | ekri | escrever |\n| manje | comer | li | ler |\n| bwè | beber | chèche | procurar |\n| achte | comprar | jwenn | encontrar/conseguir |\n\n> Exemplos combinados: Mwen bezwen dòmi. (Preciso dormir.) · Li vle aprann pale kreyòl. (Ele/ela quer aprender a falar crioulo.) · Nou pral chèche yon otèl. (Vamos procurar um hotel.) · Yo te jwenn kle a. (Eles encontraram a chave.)",
  },
  {
    title: "Negação, perguntas e conectores",
    slug: "09-negacao-perguntas-e-conectores",
    sectionNumber: 9,
    category: "Gramática" as LessonCategory,
    order: 9,
    content: "# Negação, perguntas e conectores\n\n### 9.1 Negação\n\n| PORTUGUÊS | KREYÒL |\n| --- | --- |\n| Eu não entendo. | Mwen pa konprann. |\n| Eu não trabalho hoje. | Mwen pa travay jodi a. |\n| Ele não vai vir. | Li pa pral vini. |\n| Não há problema. | Pa gen pwoblèm. |\n| Nunca. | Jamè. |\n\n### 9.2 Perguntas com palavras interrogativas\n\n| KREYÒL | PORTUGUÊS |\n| --- | --- |\n| kisa | o quê |\n| ki moun | quem |\n| kote / ki kote | onde |\n| kilè | quando |\n| poukisa | por quê |\n| kijan | como |\n| konbyen | quanto/quantos |\n| ki / kilès | qual/que |\n\n> Perguntas de sim/não geralmente começam com Èske: Èske ou pale kreyòl? = \"Você fala crioulo?\" O Èske não tem tradução literal — funciona como marcador de pergunta, semelhante a colocar \"?\" na entonação em português.\n\n| PORTUGUÊS | KREYÒL |\n| --- | --- |\n| Você fala crioulo? | Èske ou pale kreyòl? |\n| Onde você mora? | Ki kote ou rete? |\n| Por que você está aqui? | Poukisa ou la? |\n| Como posso ajudar? | Kijan mwen ka ede ou? |\n| O que você quer? | Kisa ou vle? |\n| Quem é você? | Ki moun ou ye? |\n| Quantos anos você tem? | Konbyen ane ou genyen? |\n\n### 9.3 Conectores\n\n| KREYÒL | PORTUGUÊS |\n| --- | --- |\n| ak | e/com |\n| men | mas |\n| paske | porque |\n| donk | portanto/então |\n| oswa | ou |\n| si | se |\n| lè | quando |\n| pou | para |\n| anvan | antes |\n| apre / aprè | depois |",
  },
  {
    title: "Adjetivos, advérbios e comparações",
    slug: "10-adjetivos-adverbios-e-comparacoes",
    sectionNumber: 10,
    category: "Vocabulário" as LessonCategory,
    order: 10,
    content: "# Adjetivos, advérbios e comparações\n\n| KREYÒL | PORTUGUÊS |\n| --- | --- |\n| bon | bom |\n| move | ruim/mau |\n| gwo | grande |\n| piti | pequeno |\n| bèl | bonito(a) |\n| lèd | feio(a) |\n| chè | caro |\n| bon mache | barato |\n| wouj / vèt / ble / nwa / blan | vermelho / verde / azul / preto / branco |\n\n### 10.1 Comparações\n\n| KREYÒL | PORTUGUÊS |\n| --- | --- |\n| pi ... pase | mais ... do que |\n| Otèl sa pi chè pase lòt la. | Este hotel é mais caro do que o outro. |\n| menm jan ak | igual a / da mesma forma que |\n\n### 10.2 Advérbios úteis\n\n| KREYÒL | PORTUGUÊS |\n| --- | --- |\n| anpil | muito |\n| yon ti kras | um pouquinho |\n| toujou | sempre |\n| janm / jamè | jamais/nunca |\n| byen | bem |\n| vit | rápido |\n| dousman | devagar |",
  },
  {
    title: "Números, horas e calendário",
    slug: "11-numeros-horas-e-calendario",
    sectionNumber: 11,
    category: "Vocabulário" as LessonCategory,
    order: 11,
    content: "# Números, horas e calendário\n\n### 11.1 Números de 0 a 20\n\n0 zewo · 1 youn · 2 de · 3 twa · 4 kat · 5 senk · 6 sis · 7 sèt · 8 uit · 9 nèf · 10 dis · 11 onz · 12 douz · 13 trèz · 14 katòz · 15 kenz · 16 sèz · 17 disèt · 18 dizwit · 19 diznèf · 20 ven.\n\n### 11.2 Dezenas e números maiores\n\n| NÚMERO | KREYÒL |\n| --- | --- |\n| 21 / 22 | venteyen / venn-de |\n| 30 | trant |\n| 40 | karant |\n| 50 | senkant |\n| 60 | swasant |\n| 70 | swasann-dis |\n| 80 | katreven |\n| 90 | katreven-dis |\n| 100 | san |\n| 1.000 | mil |\n\n> Prática recomendada: ensine números sempre em contexto real — preços de mercado, número do quarto de hotel, horário de ônibus — em vez de decorar a lista isolada.\n\n### 11.3 Dias, meses e expressões de tempo\n\n| KREYÒL | PORTUGUÊS |\n| --- | --- |\n| jodi a | hoje |\n| demen | amanhã |\n| yè | ontem |\n| kounye a | agora |\n| pita | mais tarde |\n| bonè | cedo |\n| anreta | tarde (atrasado) |\n| lendi, madi, mèkredi, jedi, vandredi, samdi, dimanch | segunda, terça, quarta, quinta, sexta, sábado, domingo |\n| janvye, fevriye, mas, avril, me, jen | janeiro, fevereiro, março, abril, maio, junho |\n| jiyè, out, septanm, oktòb, novanm, desanm | julho, agosto, setembro, outubro, novembro, dezembro |\n\n### 11.4 Perguntar e dizer as horas\n\n| KREYÒL | PORTUGUÊS |\n| --- | --- |\n| Ki lè li ye? | Que horas são? |\n| Li twazè. | São três horas. |\n| Li midi. | É meio-dia. |\n| Li senkè edmi. | São cinco e meia. |",
  },
  {
    title: "Família e vida cotidiana",
    slug: "12-familia-e-vida-cotidiana",
    sectionNumber: 12,
    category: "Vocabulário" as LessonCategory,
    order: 12,
    content: "# Família e vida cotidiana\n\n| PORTUGUÊS | KREYÒL | PORTUGUÊS | KREYÒL |\n| --- | --- | --- | --- |\n| família | fanmi | amigo(a) | zanmi |\n| mãe | manman | pessoa | moun |\n| pai | papa | criança | timoun |\n| filho/filha | pitit | homem | gason |\n| irmão/irmã | frè / sè | mulher | fanm |\n| marido | mari | vizinho(a) | vwazen / vwazin |\n| esposa | madanm | casa | kay |\n| avô/avó | granpapa / grann | trabalho | travay |\n\n### 12.1 Apresentando a família — mini-diálogo\n\n> Sofia: Konbyen moun ki nan fanmi ou? Ana: Nou senk: papa m, manman m, de frè m ak mwen. Sofia: Ki laj frè ou yo? Ana: Yonn gen venn-de an, lòt la gen dizwit an.\n\n> Tradução: — Quantas pessoas há na sua família? — Somos cinco: meu pai, minha mãe, meus dois irmãos e eu. — Que idade têm seus irmãos? — Um tem vinte e dois anos, o outro tem dezoito.",
  },
  {
    title: "Alimentação, compras e mercado",
    slug: "13-alimentacao-compras-e-mercado",
    sectionNumber: 13,
    category: "Diálogos" as LessonCategory,
    order: 13,
    content: "# Alimentação, compras e mercado\n\n| PORTUGUÊS | KREYÒL | PORTUGUÊS | KREYÒL |\n| --- | --- | --- | --- |\n| arroz | diri | fruta | fwi |\n| feijão | pwa | legumes/verduras | legim |\n| frango | poul | garrafa | boutèy |\n| carne | vyann | preço | pri |\n| peixe | pwason | dinheiro | lajan |\n| pão | pen | mercado | mache |\n| água | dlo | comprar | achte |\n| café | kafe | vender | vann |\n\n### 13.1 Diálogo no restaurante\n\nCliente: Bonjou. Mwen ta renmen yon plat diri ak poul, tanpri. Atendente: Wi. Èske ou vle dlo? Cliente: Wi, yon boutèy dlo, tanpri. Atendente: Men li. Bon apeti! Cliente: Konbyen sa koute? Atendente: Li koute senksan goud. Cliente: Mèsi anpil. Men lajan an.\n\n> Tradução: — Olá. Eu gostaria de um prato de arroz com frango, por favor. — Sim. Você quer água? — Sim, uma garrafa de água. — Aqui está. Bom apetite! — Quanto custa? — Custa quinhentos gourdes. — Muito obrigado(a). Aqui está o dinheiro.\n\n### 13.2 Diálogo no mercado (negociando preço)\n\n> Cliente: Konbyen mango sa yo koute? Vendedor(a): Yo koute san goud pou twa. Cliente: Se yon ti kras chè. Ou ka fè m yon pri? Vendedor(a): Oke, m ap ba ou yo pou katreven goud.\n\n> Tradução: — Quanto custam essas mangas? — Custam cem gourdes por três. — Está um pouco caro. Pode me fazer um preço melhor? — Ok, vou te dar por oitenta gourdes.",
  },
  {
    title: "Hotel e hospedagem",
    slug: "14-hotel-e-hospedagem",
    sectionNumber: 14,
    category: "Diálogos" as LessonCategory,
    order: 14,
    content: "# Hotel e hospedagem\n\n| PORTUGUÊS | KREYÒL |\n| --- | --- |\n| hotel | otèl |\n| quarto | chanm |\n| chave | kle |\n| reserva | rezèvasyon |\n| recepção | resepsyon |\n| andar | etaj |\n| check-in / entrada | anrejistreman |\n| check-out / saída | depa |\n| toalha | sèvyèt |\n| ar-condicionado | èkondisyone |\n\nRecepcionista: Bonjou. Byenveni nan otèl la. Turista: Bonjou. Mwen gen yon rezèvasyon. Recepcionista: Ki non ou? Turista: Mwen rele Ana. Recepcionista: Men kle chanm ou. Ou nan chanm nimewo katòz, dezyèm etaj. Turista: Mèsi. Èske gen wifi nan chanm nan? Recepcionista: Wi, madam. Modpas la ekri sou biwo a.\n\n> Tradução: — Olá. Bem-vindo(a) ao hotel. — Olá. Tenho uma reserva. — Qual é o seu nome? — Meu nome é Ana. — Aqui está a chave do seu quarto. Você está no quarto número catorze, segundo andar. — Obrigada. Tem wi-fi no quarto? — Sim, senhora. A senha está escrita na mesa.",
  },
  {
    title: "Aeroporto, transporte e direções",
    slug: "15-aeroporto-transporte-e-direcoes",
    sectionNumber: 15,
    category: "Diálogos" as LessonCategory,
    order: 15,
    content: "# Aeroporto, transporte e direções\n\n| PORTUGUÊS | KREYÒL | KREYÒL | PORTUGUÊS |\n| --- | --- | --- | --- |\n| aeroporto | ayewopò | ale dwat | vá à direita |\n| avião | avyon | ale agoch | vá à esquerda |\n| passaporte | paspò | ale tou dwat | siga em frente |\n| bilhete | tikè | toupre | perto |\n| bagagem | bagaj | lwen | longe |\n| táxi | taksi | devan | na frente |\n| ônibus | otobis / bis | dèyè | atrás |\n| estação | estasyon | bò kote / anfas | ao lado / em frente de |\n\n### 15.1 Pedindo direções\n\n> Turista: Eskize m, ki jan pou m rive nan estasyon otobis la? Passante: Ale tou dwat, epi vire agoch bò kote legliz la. Estasyon an toupre. Turista: Konbyen tan pou mache rive la? Passante: Sèlman senk minit.\n\n> Tradução: — Com licença, como faço para chegar à estação de ônibus? — Siga em frente e depois vire à esquerda perto da igreja. A estação é perto. — Quanto tempo demora a pé para chegar lá? — Só cinco minutos.",
  },
  {
    title: "Turismo e atendimento ao visitante",
    slug: "16-turismo-e-atendimento-ao-visitante",
    sectionNumber: 16,
    category: "Diálogos" as LessonCategory,
    order: 16,
    content: "# Turismo e atendimento ao visitante\n\n| PORTUGUÊS | KREYÒL | KREYÒL | PORTUGUÊS |\n| --- | --- | --- | --- |\n| praia | plaj | Byenveni nan Ayiti! | Bem-vindo(a) ao Haiti! |\n| montanha | mòn | Jodi a, nou pral vizite… | Hoje vamos visitar… |\n\nmuseu mize Tanpri, rete ansanm ak Por favor, permaneça junto ao gwoup la. grupo. cidade vil Si ou gen kesyon, mande m. Se tiver perguntas, pergunte-me. país peyi Tanpri, pa bliye paspò ou. Por favor, não esqueça seu fronteira fwontyè passaporte.\n\n| guia | gid | Ki sa ou ta renmen wè? | O que você gostaria de ver? |\n| --- | --- | --- | --- |\n| grupo | gwoup | Èske ou bezwen èd? | Você precisa de ajuda? |\n\n### 16.1 Fala do guia — abertura de um passeio\n\n> Byenveni, tout moun! Jodi a nou pral vizite yon bèl plaj ak yon mize istorik. Tanpri, rete ansanm ak gwoup la e pa bliye pran dlo ak yon chapo. Si ou gen kesyon nenpòt kilè, mande m san pwoblèm.\n\n> Tradução: Bem-vindos, todos! Hoje vamos visitar uma bela praia e um museu histórico. Por favor, permaneçam junto ao grupo e não esqueçam de levar água e um chapéu. Se tiverem qualquer pergunta, a qualquer momento, perguntem-me sem problema.",
  },
  {
    title: "Saúde e emergência",
    slug: "17-saude-e-emergencia",
    sectionNumber: 17,
    category: "Vocabulário" as LessonCategory,
    order: 17,
    content: "# Saúde e emergência\n\n| PORTUGUÊS | KREYÒL |\n| --- | --- |\n| ajuda | èd |\n| médico(a) | doktè |\n| hospital | lopital |\n| polícia | lapolis |\n| dor | doulè |\n| doente | malad |\n| socorro | sekou |\n| emergência | ijans |\n| febre | lafyèv |\n| remédio | medikaman |\n\n> Frases essenciais de emergência: Tanpri, mwen bezwen èd. (Por favor, preciso de ajuda.) · Rele yon doktè! (Chame um médico!) · Mwen pa santi m byen. (Não estou me sentindo bem.) · Kote lopital ki pi pre a? (Onde fica o hospital mais próximo?) · Mwen gen doulè nan vant mwen. (Estou com dor na barriga.)",
  },
  {
    title: "Cumprimentos e conversas completas",
    slug: "18-cumprimentos-e-conversas-completas",
    sectionNumber: 18,
    category: "Diálogos" as LessonCategory,
    order: 18,
    content: "# Cumprimentos e conversas completas\n\n| PORTUGUÊS | KREYÒL | PORTUGUÊS | KREYÒL |\n| --- | --- | --- | --- |\n| Olá | Bonjou! | Prazer em conhecer você | Mwen kontan rankontre ou. |\n| Boa tarde/noite | Bonswa! | Parabéns | Felisitasyon! |\n| Como você está? | Kijan ou ye? | Feliz aniversário | Bòn fèt! |\n| Estou bem | Mwen byen. | Boa viagem / boa sorte | Bon vwayaj! / Bon chans! |\n| E você? | E ou menm? | Bem-vindo(a) | Byenveni! |\n| Obrigado(a) / muito obrigado(a) | Mèsi. / Mèsi anpil. | Até logo | N a wè pita. |\n| Por favor | Tanpri. | Tchau | Babay. |\n| Desculpe | Eskize m. |  |  |\n\n### 18.1 Primeira apresentação\n\nA: Bonjou! Ki jan ou rele? B: Mwen rele Sofia. E ou menm? A: Mwen rele Marie. Ki kote ou soti? B: Mwen soti Brezil. Mwen ap aprann kreyòl. A: Poukisa ou ap aprann kreyòl? B: Mwen renmen Ayiti e mwen vle pale ak moun yo. A: Trè byen! Mwen kontan rankontre ou. B: Mwen kontan rankontre ou tou.\n\n> Tradução: — Olá! Como você se chama? — Eu me chamo Sofia. E você? — Eu me chamo Marie. De onde você é? — Sou do Brasil. Estou aprendendo crioulo. — Por que você está aprendendo crioulo? — Gosto do Haiti e quero falar com as pessoas. — Muito bem! Prazer em conhecer você. — Prazer em conhecer você também.\n\n### 18.2 Reencontro entre amigas\n\n> A: Men wi! Kijan ou ye? Sa fè lontan m pa wè ou! B: M ap boule, mèsi. E fanmi ou, kijan yo ye? A: Tout moun byen, Bondye merci. Ou gen tan pou n bwè yon kafe? B: Wi, avèk plezi!\n\n> Tradução: — Ora, olá! Como você está? Faz tempo que não te vejo! — Estou levando, obrigada. E sua família, como estão? — Todos bem, graças a Deus. Você tem tempo para tomarmos um café? — Sim, com prazer!",
  },
  {
    title: "Cultura, etiqueta e provérbios",
    slug: "19-cultura-etiqueta-e-proverbios",
    sectionNumber: 19,
    category: "Cultura" as LessonCategory,
    order: 19,
    content: "# Cultura, etiqueta e provérbios\n\n### 19.1 Etiqueta social\n\n> A saudação é essencial em qualquer interação social: pratique Bonjou e Bonswa antes de entrar diretamente no pedido — pular a saudação pode soar rude. Use tanpri e mèsi com frequência em situações de atendimento e serviço. Não presuma que uma tradução literal do português carrega o mesmo tom social em Kreyòl. No turismo, aprender palavras é apenas uma parte da comunicação — sensibilidade cultural é igualmente importante. Ensine a estudante a pedir repetição com educação: Tanpri, repete. / Pale pi dousman, tanpri. (\"Fale mais devagar, por favor.\")\n\n### 19.2 Expressões populares e provérbios\n\n> Men anpil, chay pa lou. — Muitas mãos tornam a carga leve.\n\n> Piti piti, zwazo fè nich li. — Pouco a pouco, o pássaro faz seu ninho.\n\n> Se sa ou fè, se sa ou jwenn. — Você colhe aquilo que faz.\n\n> Dèyè mòn gen mòn. — Atrás da montanha há outra montanha (a vida sempre traz novos desafios).\n\n> Bèl dan pa di zanmi. — Um belo sorriso não significa amizade verdadeira.\n\n> Cuidado didático: ensine provérbios como unidades culturais completas — evite apresentar uma tradução literal isolada como se fosse sempre equivalente ao sentido usado por um falante nativo em contexto real.",
  },
  {
    title: "Cristianismo e vocabulário bíblico",
    slug: "20-cristianismo-e-vocabulario-biblico",
    sectionNumber: 20,
    category: "Cultura" as LessonCategory,
    order: 20,
    content: "# Cristianismo e vocabulário bíblico\n\n| PORTUGUÊS | KREYÒL | PORTUGUÊS | KREYÒL |\n| --- | --- | --- | --- |\n| Deus | Bondye | amor | lanmou |\n| Jesus | Jezi | pecado | peche |\n| Cristo | Kris | perdão | padon |\n| Espírito Santo | Lespri Sen | graça | gras |\n| Bíblia | Bib la | salvação | delivrans / sali |\n| igreja | legliz | bênção / abençoar | benediksyon / beni |\n| oração | lapriyè | anjo | zanj |\n| orar | priye | discípulo / apóstolo | disip / apot |\n| fé | lafwa | evangelho | levanjil |\n| esperança | espwa | céu / amém | syèl / amèn |\n\n### 20.1 Frases cristãs\n\nBondye beni ou. · Mwen gen lafwa nan Bondye. · Ann priye. · Mwen priye pou ou. · Bondye renmen nou. · Mèsi, Bondye. · Lapè Bondye avèk ou.\n\n### 20.2 Oração simples — estrutura para praticar substituição\n\n> Bondye, mèsi pou lavi a. Mèsi pou fanmi nou. Tanpri, beni nou epi gide nou. Ban nou fòs ak sajès. Nan non Jezi. Amèn.\n\n> Tradução: Deus, obrigado pela vida. Obrigado pela nossa família. Por favor, abençoe-nos e guie-nos. Dê-nos força e sabedoria. Em nome de Jesus. Amém.\n\n> Atividade sugerida: peça à turma que substitua elementos do bloco acima — fanmi → zanmi (amigos); fòs → sajès (sabedoria); lavi a → jodi a (o dia de hoje) — para praticar a estrutura sem decorar um texto fixo.\n\n> Nota importante: para o ensino bíblico, use a edição da Bíblia em Kreyòl adotada pela igreja/comunidade da estudante, pois termos podem variar conforme a tradução e a tradição religiosa.",
  },
  {
    title: "Banco de exercícios",
    slug: "21-banco-de-exercicios",
    sectionNumber: 21,
    category: "Exercícios" as LessonCategory,
    order: 21,
    content: "# Banco de exercícios\n\nEsta seção reúne exercícios em oito estilos diferentes, organizados por tema, para variar a dinâmica das aulas: transformação, preenchimento de lacunas, múltipla escolha, verdadeiro ou falso, tradução, associação de colunas, ordenação de frases e produção livre/role-play. O gabarito completo está na seção 24.\n\n#### Exercício 1 — Transformação de sujeito\n*Categoria: Verbos*\n\n> Reescreva a frase \"Mwen ap travay.\" trocando o sujeito para cada pronome indicado:\n\n- 1. ou →\n- 2. li →\n- 3. nou →\n- 4. yo →\n\n#### Exercício 2 — Tempos verbais\n*Categoria: Verbos*\n\n> Transforme \"Mwen manje.\" para os tempos indicados:\n\n- 1. Passado:\n- 2. Progressivo:\n- 3. Futuro próximo:\n- 4. Condicional:\n\n#### Exercício 3 — Complete a lacuna\n*Categoria: Preenchimento*\n\n> Complete cada frase com a palavra correta do quadro: pa · yo · te · tanpri · kisa\n\n- 1. Mwen                      konprann sa ou di a.\n- 2. Liv                    sou tab la. (os livros)\n- 3. Nou                     vizite mize a yè.\n- 4. Ban m dlo,                    .\n- 5.                    ou vle manje?\n\n#### Exercício 4 — Negação\n*Categoria: Gramática*\n\n> Transforme cada frase em negativa:\n\n- 1. Mwen konprann. →\n- 2. Li vle vini. →\n- 3. Nou gen lajan. →\n\n#### Exercício 5 — Múltipla escolha\n*Categoria: Vocabulário*\n\n- 1. \"Onde você mora?\" em Kreyòl é:\n- (a) Kilè ou rete?\n- (b) Ki kote ou rete?\n- (c) Kisa ou rete?\n- 2. \"Otèl\" significa:\n- (a) hospital\n- (b) hotel\n- (c) escola\n- 3. A partícula que indica futuro próximo é:\n- (a) te\n- (b) pral\n- (c) pa\n- 4. \"Mèsi anpil\" significa:\n- (a) de nada\n- (b) muito obrigado(a)\n- (c) com licença\n\n#### Exercício 6 — Verdadeiro ou falso\n*Categoria: Gramática e cultura*\n\n- 1. Kreyòl Ayisyen e Kreyòl Gwadloup são exatamente a mesma língua. ( V / F )\n- 2. O adjetivo em Kreyòl geralmente vem depois do substantivo. ( V / F )\n- 3. A palavra ou em Kreyòl significa a conjunção \"ou\" do português. ( V / F )\n- 4. O determinante definido em Kreyòl vem depois do substantivo (ex.: liv la). ( V / F )\n- 5. O Kreyòl Ayisyen tem conjugação verbal por pessoa, como o português. ( V / F )\n\n#### Exercício 7 — Tradução (PT → KR)\n*Categoria: Tradução*\n\n- 1. Eu preciso de ajuda. →\n- 2. Quanto custa isso? →\n- 3. Vá em frente e depois vire à direita. →\n- 4. Eu tenho uma reserva no hotel. →\n- 5. Deus te abençoe. →\n\n#### Exercício 8 — Tradução (KR → PT)\n*Categoria: Tradução*\n\n- 1. Konbyen ane ou genyen? →\n- 2. Nou pral chèche yon taksi. →\n- 3. Li pa santi l byen jodi a. →\n- 4. Piti piti, zwazo fè nich li. →\n\n#### Exercício 9 — Associação de colunas\n*Categoria: Vocabulário*\n\n> Ligue cada palavra em Kreyòl (coluna A) ao seu significado em português (coluna B):\n\n| COLUNA A | COLUNA B |\n| --- | --- |\n| 1. otèl | a. mercado |\n| 2. mache | b. hospital |\n| 3. lopital | c. hotel |\n| 4. legliz | d. praia |\n| 5. plaj | e. igreja |\n| Exercício 10 — Perguntas e respostas | Produção guiada |\n\n> Escreva uma pergunta usando cada palavra interrogativa, e depois responda com uma frase completa:\n\n- 1. kote → Pergunta:                     Resposta:\n- 2. kisa → Pergunta:                    Resposta:\n- 3. ki moun → Pergunta:                      Resposta:\n- 4. kilè → Pergunta:                    Resposta:\n- 5. konbyen → Pergunta:                      Resposta:\n\n#### Exercício 11 — Ordene a frase\n*Categoria: Sintaxe*\n\n> Coloque as palavras na ordem correta para formar uma frase em Kreyòl:\n\n- 1. diri / manje / mwen →\n- 2. otèl / bezwen / yon / mwen →\n- 3. kreyòl / ap / aprann / li →\n- 4. chè / machin / la / pi / pase / lòt / la →\n\n#### Exercício 12 — Turismo: produção livre\n*Categoria: Produção livre*\n\n> Escreva 5 frases que um(a) guia turístico(a) diria a um grupo de visitantes recém-chegados a uma praia haitiana.\n\n#### Exercício 13 — Igreja: produção livre\n*Categoria: Produção livre*\n\n> Escreva 5 frases relacionadas a uma reunião cristã (convite, boas-vindas, oração, agradecimento).\n\n#### Exercício 14 — Role-play em duplas\n*Categoria: Conversação*\n\n> Em duplas, encenem cada situação usando o vocabulário das seções correspondentes. Cada diálogo deve ter no mínimo 6 falas.\n\n- 1. Role-play A: um(a) turista chega ao Haiti e encontra um(a) guia no aeroporto.\n- 2. Role-play B: um(a) cliente compra comida em um mercado e negocia o preço.\n- 3. Role-play C: um(a) hóspede faz check-in em um hotel e pergunta sobre wi-fi e café da manhã.\n- 4. Role-play D: um(a) visitante pergunta como chegar a uma igreja e agradece pela ajuda.\n- 5. Role-play E: duas pessoas se apresentam pela primeira vez e descobrem de onde cada uma é.\n- 6. Role-play F (novo): um(a) paciente explica a um(a) médico(a) que está com dor e febre.\n- 7. Role-play G (novo): duas amigas se reencontram depois de muito tempo e trocam notícias da família.\n\n#### Exercício 15 — Correção de erros\n*Categoria: Revisão*\n\n> Cada frase abaixo tem um erro de gramática ou de ordem das palavras. Reescreva corretamente:\n\n- 1. Mwen wouj machin gen. →\n- 2. La liv sou tab la. →\n- 3. Pa mwen konprann. →\n- 4. Ou pral ki kote? →\n\n#### Exercício 16 — Ditado guiado (para a professora ler em voz alta)\n*Categoria: Compreensão oral*\n\n> A professora lê cada frase duas vezes; o aluno escreve o que ouviu e depois traduz.\n\n- 1. Mwen rele Ana e mwen soti Brezil.\n- 2. Nou pral vizite yon mize demen.\n- 3. Konbyen sa koute, tanpri?\n- 4. Bondye beni fanmi ou.",
  },
  {
    title: "Plano de 20 aulas",
    slug: "22-plano-de-20-aulas",
    sectionNumber: 22,
    category: "Referência" as LessonCategory,
    order: 22,
    content: "# Plano de 20 aulas\n\n| AULA | CONTEÚDO | TAREFA PRÁTICA |\n| --- | --- | --- |\n| 1 | Saudações + sons | Apresentação de 1 minuto |\n| 2 | Pronomes + frases | 20 frases SVO |\n| 3 | Perguntas | Entrevista entre colegas |\n| 4 | Negação | Jogo verdadeiro/falso (Ex. 6) |\n| 5 | Determinantes e plural | Descrever objetos da sala |\n| 6 | Tempo/aspecto (te/ap/pral/ta) | Narrar ontem/hoje/amanhã |\n| 7 | Números e horas | Preços e quantidades |\n| 8 | Compras e mercado | Role-play B |\n| 9 | Restaurante | Pedir uma refeição |\n| 10 | Hotel | Role-play C (check-in) |\n| 11 | Transporte e direções | Pedir direções na rua |\n| 12 | Aeroporto | Simulação de viagem |\n| 13 | Turismo | Role-play A (guia) |\n| 14 | Família | Apresentar a própria família |\n| 15 | Saúde e emergência | Role-play F (consulta) |\n| 16 | Cultura, etiqueta e provérbios | Explicar 2 provérbios |\n| 17 | Vocabulário cristão | Escrever uma oração curta |\n| 18 | Leitura bíblica e frases cristãs | Role-play D + Exercício 13 |\n| 19 | Conversação geral | Simulação completa (Ex. 14) |\n| 20 | Avaliação | Conversa de 15 minutos (seção 23) |",
  },
  {
    title: "Avaliação final da estudante",
    slug: "23-avaliacao-final-da-estudante",
    sectionNumber: 23,
    category: "Referência" as LessonCategory,
    order: 23,
    content: "# Avaliação final da estudante\n\nA avaliação pode ser feita sem nota numérica, usando quatro níveis: iniciante, em desenvolvimento, funcional e autônoma em situações simples. Marque cada item observado durante a conversa final:\n\n- [ ] Cumprimenta e se despede\n- [ ] Apresenta nome e origem\n- [ ] Faz e responde perguntas básicas\n- [ ] Compra comida e pergunta preços\n- [ ] Faz check-in em hotel\n- [ ] Pede e entende direções simples\n- [ ] Participa de uma conversa turística curta\n- [ ] Reconhece vocabulário cristão essencial\n- [ ] Pede que o interlocutor repita/fale mais devagar\n- [ ] Sustenta uma conversa simples por 10–15 min",
  },
  {
    title: "Gabarito completo",
    slug: "24-gabarito-completo",
    sectionNumber: 24,
    category: "Referência" as LessonCategory,
    order: 24,
    content: "# Gabarito completo\n\nEx. 1: Ou ap travay. / Li ap travay. / Nou ap travay. / Yo ap travay. Ex. 2: Mwen te manje. / Mwen ap manje. / Mwen pral manje. / Mwen ta manje. Ex. 3: 1. pa — 2. yo — 3. te — 4. tanpri — 5. Kisa Ex. 4: Mwen pa konprann. / Li pa vle vini. / Nou pa gen lajan. Ex. 5: 1-b · 2-b · 3-b · 4-b Ex. 6: 1-F · 2-V · 3-F · 4-V · 5-F Ex. 7: 1. Mwen bezwen èd. — 2. Konbyen sa koute? — 3. Ale tou dwat epi vire adwat. — 4. Mwen gen yon rezèvasyon nan otèl la. — 5. Bondye beni ou. Ex. 8: 1. Quantos anos você tem? — 2. Vamos procurar um táxi. — 3. Ele/ela não está se sentindo bem hoje. — 4. Pouco a pouco, o pássaro faz seu ninho. Ex. 9: 1-c · 2-a · 3-b · 4-e · 5-d Ex. 10: resposta livre, desde que a pergunta respeite a função da palavra interrogativa indicada. Ex. 11: 1. Mwen manje diri. — 2. Mwen bezwen yon otèl. — 3. Li ap aprann kreyòl. — 4. Machin la pi chè pase lòt la. Ex. 12 e 13: produção livre — avaliar uso correto de vocabulário e estruturas das seções 16 e 20. Ex. 14: avaliação por observação direta durante a encenação. Ex. 15: 1. Mwen gen yon machin wouj. — 2. Liv la sou tab la. — 3. Mwen pa konprann. — 4. Ou pral ki kote? Ex. 16: 1. Eu me chamo Ana e sou do Brasil. — 2. Vamos visitar um museu amanhã. — 3. Quanto custa isso, por favor? — 4. Deus abençoe sua família.",
  },
  {
    title: "Guia rápido — 60 frases essenciais",
    slug: "25-guia-rapido-60-frases-essenciais",
    sectionNumber: 25,
    category: "Referência" as LessonCategory,
    order: 25,
    content: "# Guia rápido — 60 frases essenciais\n\nBonjou! · Kijan ou ye? · Mwen byen. · E ou menm? · Mèsi anpil. · Tanpri. · Eskize m. · Mwen pa konprann. · Pale pi dousman, tanpri. · Tanpri, repete. Ki jan ou rele? · Mwen rele… · Ki kote ou soti? · Mwen soti… · Ki kote ou rete? · Kisa sa ye? · Ki moun li ye? · Ki kote sa ye? · Kilè ou vini? · Poukisa ou la?\n\nKijan mwen ka ede ou? · Konbyen sa koute? · Mwen ta renmen… · Mwen bezwen èd. · Mwen gen yon rezèvasyon. · Ki kote otèl la ye? · Ki kote twalèt la ye? · Mwen bezwen yon taksi. · Ale dwat. · Ale agoch. Mwen vle achte sa. · Mwen pa vle sa. · Ban mwen dlo, tanpri. · Mwen grangou. · Mwen swaf. · Bon vwayaj! · Byenveni! · Felisitasyon! · Bòn fèt! · Bon chans! N a wè pita. · Babay. · Bondye beni ou. · Ann priye. · Mwen gen lafwa nan Bondye. · Mwen priye pou ou. · Mèsi, Bondye. · Lapè Bondye avèk ou. · Mwen ap aprann kreyòl. · Mwen renmen pale kreyòl.\n\nKonbyen ane ou genyen? · Ki lè li ye? · Mwen gen yon sè ak yon frè. · Nou se zanmi. · Li pa santi l byen. · Rele yon doktè! · Kote lopital ki pi pre a? · Èske gen wifi la a? · Chanm nan bèl anpil. · Mèsi pou tout bagay.",
  },
  {
    title: "Referências para aprofundamento",
    slug: "26-referencias-para-aprofundamento",
    sectionNumber: 26,
    category: "Referência" as LessonCategory,
    order: 26,
    content: "# Referências para aprofundamento\n\nAkademi Kreyòl Ayisyen (AKA) — informações institucionais, ortografia e desenvolvimento de ferramentas linguísticas. Michel DeGraff — \"Kreyòl Ayisyen, or Haitian Creole\", capítulo em Comparative Creole Syntax. Dominique Fattier — \"Haitian Creole\", descrição gramatical no Atlas of Pidgin and Creole Languages. Claire Lefebvre — estudo sobre o sistema de tempo, modo e aspecto do Kreyòl Ayisyen. Robert Damoiseau — gramática comparada do francês e do crioulo guianense. Ralph Ludwig, Danièle Montbrand e Hector Pullet — dicionário/gramática do crioulo de Guadalupe. Chris Corne — gramática do Morisyen.\n\n> Nota final para a professora: combine esta apostila com áudio de falantes nativos, exercícios de escuta, leitura em voz alta e conversas espontâneas. Lembre sempre a turma de que crioulos são línguas individuais — o Kreyòl Ayisyen deve ser ensinado pelas suas próprias regras, mesmo quando existirem semelhanças com outros crioulos.",
  },
];